name: Publish NuGet.org

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update package

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
        
      - name: Building
        run: dotnet build --nologo
          
      - name: Testing
        run: dotnet test --nologo
        
      - name: Packing
        run: dotnet pack -c Release --nologo
        
      - name: Publishing
        run: dotnet nuget push "**/*.nupkg" -k ${{ secrets.NuGetApiKey }} --skip-duplicate -s https://api.nuget.org/v3/index.json
